--------------------------------------------------------
-- Archivo creado  - domingo-julio-12-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ALUMNOS
--------------------------------------------------------

  CREATE TABLE "BD2014"."ALUMNOS" 
   (	"CI" NUMBER(11,0), 
	"nombre" VARCHAR2(50 BYTE), 
	"direccion" VARCHAR2(100 BYTE), 
	"sexo" VARCHAR2(1 BYTE), 
	"pais" VARCHAR2(50 BYTE), 
	"musica" VARCHAR2(1 BYTE), 
	"deporte" VARCHAR2(1 BYTE), 
	"cine" VARCHAR2(1 BYTE), 
	"email" VARCHAR2(50 BYTE), 
	"clave" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ATLETAS
--------------------------------------------------------

  CREATE TABLE "BD2014"."ATLETAS" 
   (	"CI" VARCHAR2(100 CHAR), 
	"NOMBRE" VARCHAR2(100 CHAR), 
	"APELLIDO" VARCHAR2(100 CHAR), 
	"FECHA" VARCHAR2(100 CHAR), 
	"ESTADO_CIVIL" VARCHAR2(100 CHAR), 
	"TIPO_SANGRE" VARCHAR2(20 CHAR), 
	"GENERO" VARCHAR2(1 CHAR), 
	"LUGAR_NACIMIENTO" VARCHAR2(100 CHAR), 
	"DIRECCION" VARCHAR2(100 CHAR), 
	"EMAIL" VARCHAR2(100 CHAR), 
	"TELEFONO" VARCHAR2(100 CHAR), 
	"INGRESO" VARCHAR2(100 CHAR), 
	"SEMESTRE" VARCHAR2(100 CHAR), 
	"PROMEDIO" VARCHAR2(100 CHAR), 
	"ESTATUS" VARCHAR2(3 CHAR), 
	"SEDE" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENTRENADORES
--------------------------------------------------------

  CREATE TABLE "BD2014"."ENTRENADORES" 
   (	"ID" NUMBER(20,0), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"SALARY" NUMBER, 
	"EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAGOS
--------------------------------------------------------

  CREATE TABLE "BD2014"."PAGOS" 
   (	"CI" VARCHAR2(20 BYTE), 
	"TIPO" VARCHAR2(20 BYTE), 
	"MONTO" VARCHAR2(20 BYTE), 
	"REFERENCIA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BD2014.ALUMNOS
Insert into BD2014.ALUMNOS (CI,"nombre","direccion","sexo","pais","musica","deporte","cine","email","clave") values (456,'vbnkm',' ghjk','M','Venezuela','1','1','1','cnaci@caca.com','12345678');
Insert into BD2014.ALUMNOS (CI,"nombre","direccion","sexo","pais","musica","deporte","cine","email","clave") values (678,'ghj','hj','M','Venezuela','0','1','0','cccs@csac.com','12345678');
Insert into BD2014.ALUMNOS (CI,"nombre","direccion","sexo","pais","musica","deporte","cine","email","clave") values (17299596,'urimare ','quinta crespo','F','Venezuela','0','1','0','urimare155@hotmail.com','123');
REM INSERTING into BD2014.ATLETAS
Insert into BD2014.ATLETAS (CI,NOMBRE,APELLIDO,FECHA,ESTADO_CIVIL,TIPO_SANGRE,GENERO,LUGAR_NACIMIENTO,DIRECCION,EMAIL,TELEFONO,INGRESO,SEMESTRE,PROMEDIO,ESTATUS,SEDE) values ('17692816','Adalberto','Toledo','20 de febrero 1987','soltero','ORH+','M','caracas','quinta crespo','none14@none.com','04160142958','hnnb','hcngfhcg','10','001','001');
REM INSERTING into BD2014.ENTRENADORES
Insert into BD2014.ENTRENADORES (ID,FIRST_NAME,LAST_NAME,SALARY,EMAIL) values (1,'uri','rodriguez',9999999,'none@none.com');
Insert into BD2014.ENTRENADORES (ID,FIRST_NAME,LAST_NAME,SALARY,EMAIL) values (32232,'sdfg','sdfgh',4567,'sdfghj@sdfgh.com');
Insert into BD2014.ENTRENADORES (ID,FIRST_NAME,LAST_NAME,SALARY,EMAIL) values (17299596,'urimare','rodriguez',34536465,'urimare155@hotmail.com');
REM INSERTING into BD2014.PAGOS
Insert into BD2014.PAGOS (CI,TIPO,MONTO,REFERENCIA) values ('1','1','1','1');
--------------------------------------------------------
--  DDL for Index EMPLOYEES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2014"."EMPLOYEES_PK" ON "BD2014"."ENTRENADORES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ATLETAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2014"."ATLETAS_PK" ON "BD2014"."ATLETAS" ("CI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ENTRENADORES
--------------------------------------------------------

  ALTER TABLE "BD2014"."ENTRENADORES" ADD CONSTRAINT "EMPLOYEES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BD2014"."ENTRENADORES" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ENTRENADORES" MODIFY ("SALARY" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ENTRENADORES" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ENTRENADORES" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ENTRENADORES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ATLETAS
--------------------------------------------------------

  ALTER TABLE "BD2014"."ATLETAS" MODIFY ("SEDE" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ATLETAS" ADD CONSTRAINT "ATLETAS_PK" PRIMARY KEY ("CI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BD2014"."ATLETAS" MODIFY ("ESTATUS" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ATLETAS" MODIFY ("PROMEDIO" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ATLETAS" MODIFY ("SEMESTRE" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ATLETAS" MODIFY ("INGRESO" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ATLETAS" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ATLETAS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ATLETAS" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ATLETAS" MODIFY ("LUGAR_NACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ATLETAS" MODIFY ("GENERO" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ATLETAS" MODIFY ("TIPO_SANGRE" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ATLETAS" MODIFY ("ESTADO_CIVIL" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ATLETAS" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ATLETAS" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ATLETAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ATLETAS" MODIFY ("CI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ALUMNOS
--------------------------------------------------------

  ALTER TABLE "BD2014"."ALUMNOS" MODIFY ("clave" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ALUMNOS" MODIFY ("email" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ALUMNOS" MODIFY ("cine" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ALUMNOS" MODIFY ("deporte" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ALUMNOS" MODIFY ("musica" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ALUMNOS" MODIFY ("pais" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ALUMNOS" MODIFY ("sexo" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ALUMNOS" MODIFY ("direccion" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ALUMNOS" MODIFY ("nombre" NOT NULL ENABLE);
  ALTER TABLE "BD2014"."ALUMNOS" MODIFY ("CI" NOT NULL ENABLE);
