CREATE TABLESPACE USERS
  DATAFILE 'USERS.dat' 
    SIZE 20M
  ONLINE;

  

CREATE USER BD2014
  IDENTIFIED BY bd2014
  DEFAULT TABLESPACE USERS
  QUOTA 20M on USERS;
  
  grant create session to BD2014; 
  
  GRANT create session TO BD2014;
GRANT create table TO BD2014;
GRANT create view TO BD2014;
GRANT create any trigger TO BD2014;
GRANT create any procedure TO BD2014;
GRANT create sequence TO BD2014;
GRANT create synonym TO BD2014;


CREATE TABLE "BD2014"."ALUMNOS"
  (
  "id" NUMBER(11) NOT NULL,
  "nombre"  VARCHAR2(50 BYTE) NOT NULL,
  "direccion"  VARCHAR2(100 BYTE) NOT NULL,
  "sexo"  VARCHAR2(1 BYTE) NOT NULL,
  "pais"  VARCHAR2(50 BYTE) NOT NULL,
  "musica" VARCHAR2(1 BYTE) NOT NULL,
  "deporte" VARCHAR2(1 BYTE) NOT NULL,
  "cine" VARCHAR2(1 BYTE) NOT NULL,
  "email" VARCHAR2(50 BYTE) NOT NULL,
  "clave" VARCHAR2(50 BYTE) NOT NULL
  ) TABLESPACE "USERS" ;

  
 CREATE TABLE BD2014.EMPLOYEES 
(
  ID NUMBER(20, 0) NOT NULL 
, FIRST_NAME VARCHAR2(20) NOT NULL 
, LAST_NAME VARCHAR2(20) NOT NULL 
, JOB_ID NUMBER(10, 0) NOT NULL 
, SALARY NUMBER NOT NULL 
, EMAIL VARCHAR2(50) NOT NULL 
, CONSTRAINT EMPLOYEES_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
)